const CACHE_NAME = 'empire-sprites-v1';

const STATIC_SPRITES = [
  // Bases
  '/assets/sprites/bases/base.webp',
  '/assets/sprites/bases/base_stone.webp',
  '/assets/sprites/bases/base_neolithicum.webp',
  '/assets/sprites/bases/base_bronze.webp',
  '/assets/sprites/bases/base_iron.webp',
  '/assets/sprites/bases/base_middle_ages.webp',
  '/assets/sprites/bases/base_renaissance.webp',
  '/assets/sprites/bases/base_industrial.webp',
  '/assets/sprites/bases/base_modern.webp',
  '/assets/sprites/bases/base_future.webp',
  '/assets/sprites/bases/path.webp',
  '/assets/sprites/bases/spawnpoint.webp',
  // Map / textures
  '/assets/sprites/images/texture.webp',
  '/assets/sprites/images/tctd.webp',
  '/assets/sprites/maps/map.webp',
  // HUD
  '/assets/sprites/hud/arrow.webp',
  '/assets/sprites/hud/bolt.webp',
  '/assets/sprites/hud/fireball.webp',
  '/assets/sprites/hud/flying_coin.webp',
  '/assets/sprites/hud/flying_hearth.webp',
  '/assets/sprites/hud/iceball.webp',
  '/assets/sprites/hud/shot.webp',
  '/assets/sprites/hud/tarball.webp',
  // Shots (WebP; ~55% smaller than PNG originals)
  '/assets/sprites/shots/cold_explosion.webp',
  '/assets/sprites/shots/dust_explosion.webp',
  '/assets/sprites/shots/explosion.webp',
  '/assets/sprites/shots/explosion2.webp',
  // Structures
  '/assets/sprites/structures/arbeleste_tower/arbeleste_tower.webp',
  '/assets/sprites/structures/arrow_tower/arrow_tower.webp',
  '/assets/sprites/structures/ballista_tower/ballista_tower.webp',
  '/assets/sprites/structures/basic_tower/basic_tower.webp',
  '/assets/sprites/structures/boiling_oil/boiling_oil.webp',
  '/assets/sprites/structures/bunker/bunker.webp',
  '/assets/sprites/structures/cannon_tower/cannon_tower.webp',
  '/assets/sprites/structures/catapults/catapults.webp',
  '/assets/sprites/structures/cold_tower/cold_tower.webp',
  '/assets/sprites/structures/double_sling_tower/double_sling_tower.webp',
  '/assets/sprites/structures/fire_tower/fire_tower.webp',
  '/assets/sprites/structures/flame_thrower/flame_thrower.webp',
  '/assets/sprites/structures/gatling_tower/gatling_tower.webp',
  '/assets/sprites/structures/heavy_tower/heavy_tower.webp',
  '/assets/sprites/structures/ice_tower/ice_tower.webp',
  '/assets/sprites/structures/mg_bunker/mg_bunker.webp',
  '/assets/sprites/structures/napalm_tower/napalm_tower.webp',
  '/assets/sprites/structures/paralyzing_tower/paralyzing_tower.webp',
  '/assets/sprites/structures/rapid_mg_tower/rapid_mg_tower.webp',
  '/assets/sprites/structures/rifle_tower/rifle_tower.webp',
  '/assets/sprites/structures/rocket_tower/rocket_tower.webp',
  '/assets/sprites/structures/shock_tower/shock_tower.webp',
  '/assets/sprites/structures/sling_tower/sling_tower.webp',
  '/assets/sprites/structures/sniper_tower/sniper_tower.webp',
  '/assets/sprites/structures/spike_trap/spike_trap.webp',
  '/assets/sprites/structures/tar_tower/tar_tower.webp',
  '/assets/sprites/structures/torch_tower/torch_tower.webp',
  // Critters
  '/assets/sprites/critters/bowman/bowman.png',
  '/assets/sprites/critters/cargo/cargo.webp',
  '/assets/sprites/critters/cart/cart.png',
  '/assets/sprites/critters/chariot/chariot.webp',
  '/assets/sprites/critters/clubman/clubman.webp',
  '/assets/sprites/critters/condotteri/condotteri.webp',
  '/assets/sprites/critters/crusader/crusader.webp',
  '/assets/sprites/critters/dragooner/dragooner.webp',
  '/assets/sprites/critters/handgunner/handgunner.webp',
  '/assets/sprites/critters/heli/heli.webp',
  '/assets/sprites/critters/horseman_fast/horseman_fast.webp',
  '/assets/sprites/critters/horseman_slow/horseman_slow.png',
  '/assets/sprites/critters/knight/knight.webp',
  '/assets/sprites/critters/large_cart/large_cart.webp',
  '/assets/sprites/critters/legionary/legionary.webp',
  '/assets/sprites/critters/light_cavalry/light_cavalry.webp',
  '/assets/sprites/critters/mech_warrior/mech_warrior.webp',
  '/assets/sprites/critters/motorbike/motorbike.webp',
  '/assets/sprites/critters/musketeer/musketeer.webp',
  '/assets/sprites/critters/ninja/ninja.webp',
  '/assets/sprites/critters/old_soldier/soldier.png',
  '/assets/sprites/critters/pikeneer/pikeneer.png',
  '/assets/sprites/critters/samurai/samurai.webp',
  '/assets/sprites/critters/scout/scout.webp',
  '/assets/sprites/critters/siege_ram/siege_ram.webp',
  '/assets/sprites/critters/siege_tank/siege_tank.webp',
  '/assets/sprites/critters/slave/slave.png',
  '/assets/sprites/critters/small_tank/small_tank.webp',
  '/assets/sprites/critters/soldier/soldier.webp',
  '/assets/sprites/critters/specops/specops.webp',
  '/assets/sprites/critters/swordman/swordman.png',
  '/assets/sprites/critters/the_general/the_general.png',
  '/assets/sprites/critters/the_king/the_king.png',
  '/assets/sprites/critters/the_swordmaster/the_swordmaster.webp',
  '/assets/sprites/critters/transporter/transporter.webp',
  '/assets/sprites/critters/war_carriage/war_carriage.webp',
  '/assets/sprites/critters/warrior/warrior.png',
  // Buildings
  '/assets/sprites/buildings/academy/academy.webp',
  '/assets/sprites/buildings/airfield/airfield.webp',
  '/assets/sprites/buildings/archives/archives.webp',
  '/assets/sprites/buildings/arts_gallery/arts_gallery.webp',
  '/assets/sprites/buildings/barracks/barracks.webp',
  '/assets/sprites/buildings/castle/castle.webp',
  '/assets/sprites/buildings/chapel/chapel.webp',
  '/assets/sprites/buildings/church/church.webp',
  '/assets/sprites/buildings/cryptographers_guild/cryptographers_guild.webp',
  '/assets/sprites/buildings/defense_department/defense_department.webp',
  '/assets/sprites/buildings/earth_wall/earth_wall.webp',
  '/assets/sprites/buildings/echelon_defense_facility/echelon_defense_facility.webp',
  '/assets/sprites/buildings/electric_fence/electric_fence.webp',
  '/assets/sprites/buildings/emergency_room/emergency_room.webp',
  '/assets/sprites/buildings/emperors_palace/emperors_palace.webp',
  '/assets/sprites/buildings/epic_drawings/epic_drawings.webp',
  '/assets/sprites/buildings/exchange_post/exchange_post.webp',
  '/assets/sprites/buildings/executive_carpool/executive_carpool.webp',
  '/assets/sprites/buildings/fire_place/fire_place.webp',
  '/assets/sprites/buildings/forge/forge.webp',
  '/assets/sprites/buildings/granary/granary.webp',
  '/assets/sprites/buildings/guild/guild.webp',
  '/assets/sprites/buildings/gunsmith/gunsmith.webp',
  '/assets/sprites/buildings/hangar/hangar.webp',
  '/assets/sprites/buildings/harbor/harbor.webp',
  '/assets/sprites/buildings/hospital/hospital.webp',
  '/assets/sprites/buildings/intelligence_agency/intelligence_agency.webp',
  '/assets/sprites/buildings/library/library.webp',
  '/assets/sprites/buildings/lore_collection/lore_collection.webp',
  '/assets/sprites/buildings/manor/manor.webp',
  '/assets/sprites/buildings/mech_warrior_lab/mech_warrior_lab.webp',
  '/assets/sprites/buildings/medicus/medicus.webp',
  '/assets/sprites/buildings/navigation_system/navigation_system.webp',
  '/assets/sprites/buildings/race_course/race_course.webp',
  '/assets/sprites/buildings/rail_roads/rail_roads.webp',
  '/assets/sprites/buildings/research_lab/research_lab.webp',
  '/assets/sprites/buildings/research_vault/research_vault.webp',
  '/assets/sprites/buildings/robo_manufacture/robo_manufacture.webp',
  '/assets/sprites/buildings/rocket_silo/rocket_silo.webp',
  '/assets/sprites/buildings/sovereign_guard/sovereign_guard.webp',
  '/assets/sprites/buildings/stock_market/stock_market.webp',
  '/assets/sprites/buildings/stone_circle/stone_circle.webp',
  '/assets/sprites/buildings/sword_maker/sword_maker.webp',
  '/assets/sprites/buildings/the_kings_lair/the_kings_lair.webp',
  '/assets/sprites/buildings/the_world_wonder/the_world_wonder.webp',
  '/assets/sprites/buildings/theater/theater.webp',
  '/assets/sprites/buildings/tool_shop/tool_shop.webp',
  '/assets/sprites/buildings/treadwheel_crane/treadwheel_crane.webp',
  '/assets/sprites/buildings/treasure_chamber/treasure_chamber.webp',
  '/assets/sprites/buildings/university/university.webp',
  '/assets/sprites/buildings/wmd_site/wmd_site.webp',
  '/assets/sprites/buildings/work_shop/work_shop.webp',
  // Knowledge
  '/assets/sprites/knowledge/aero_dynamics/aero_dynamics.webp',
  '/assets/sprites/knowledge/agriculture/agriculture.webp',
  '/assets/sprites/knowledge/alphabet_writing/alphabet_writing.webp',
  '/assets/sprites/knowledge/architecture/architecture.webp',
  '/assets/sprites/knowledge/arts/arts.webp',
  '/assets/sprites/knowledge/aviation/aviation.webp',
  '/assets/sprites/knowledge/ballistics/ballistics.webp',
  '/assets/sprites/knowledge/bionics/bionics.webp',
  '/assets/sprites/knowledge/cartography/cartography.webp',
  '/assets/sprites/knowledge/chemical_warfare/chemical_warfare.webp',
  '/assets/sprites/knowledge/chemistry/chemistry.webp',
  '/assets/sprites/knowledge/civil_engineering/civil_engineering.webp',
  '/assets/sprites/knowledge/cold_fusion/cold_fusion.webp',
  '/assets/sprites/knowledge/combustion_engine/combustion_engine.webp',
  '/assets/sprites/knowledge/command_chain/command_chain.webp',
  '/assets/sprites/knowledge/computer_technology/computer_technology.webp',
  '/assets/sprites/knowledge/constitution/constitution.webp',
  '/assets/sprites/knowledge/copper_bronze/copper_bronze.webp',
  '/assets/sprites/knowledge/craftsmanship/craftsmanship.webp',
  '/assets/sprites/knowledge/cryptology/cryptology.webp',
  '/assets/sprites/knowledge/currency/currency.webp',
  '/assets/sprites/knowledge/domestication/domestication.webp',
  '/assets/sprites/knowledge/drill/drill.webp',
  '/assets/sprites/knowledge/economy/economy.webp',
  '/assets/sprites/knowledge/electricity/electricity.webp',
  '/assets/sprites/knowledge/electronics/electronics.webp',
  '/assets/sprites/knowledge/fanatism/fanatism.webp',
  '/assets/sprites/knowledge/feudalism/feudalism.webp',
  '/assets/sprites/knowledge/fiber_composite/fiber_composite.webp',
  '/assets/sprites/knowledge/globalization_strategies/globalization_strategies.webp',
  '/assets/sprites/knowledge/gunpowder/gunpowder.webp',
  '/assets/sprites/knowledge/herbology/herbology.webp',
  '/assets/sprites/knowledge/holy_war/holy_war.webp',
  '/assets/sprites/knowledge/horseback_riding/horseback_riding.webp',
  '/assets/sprites/knowledge/hunting/hunting.webp',
  '/assets/sprites/knowledge/iron/iron.webp',
  '/assets/sprites/knowledge/kno_armour/kno_armour.webp',
  '/assets/sprites/knowledge/laws/laws.webp',
  '/assets/sprites/knowledge/literature/literature.webp',
  '/assets/sprites/knowledge/mass_production/mass_production.webp',
  '/assets/sprites/knowledge/mathmatics/mathmatics.webp',
  '/assets/sprites/knowledge/mechanical_engineering/mechanical_engineering.webp',
  '/assets/sprites/knowledge/mechanics/mechanics.webp',
  '/assets/sprites/knowledge/medicine/medicine.webp',
  '/assets/sprites/knowledge/military_service/military_service.webp',
  '/assets/sprites/knowledge/monarchy/monarchy.webp',
  '/assets/sprites/knowledge/music/music.webp',
  '/assets/sprites/knowledge/mystic/mystic.webp',
  '/assets/sprites/knowledge/nuclear_reaction/nuclear_reaction.webp',
  '/assets/sprites/knowledge/optics/optics.webp',
  '/assets/sprites/knowledge/painting/painting.webp',
  '/assets/sprites/knowledge/physics/physics.webp',
  '/assets/sprites/knowledge/pottery/pottery.webp',
  '/assets/sprites/knowledge/printing_press/printing_press.webp',
  '/assets/sprites/knowledge/religion/religion.webp',
  '/assets/sprites/knowledge/rocket_science/rocket_science.webp',
  '/assets/sprites/knowledge/sailing/sailing.webp',
  '/assets/sprites/knowledge/sanitation/sanitation.webp',
  '/assets/sprites/knowledge/satellite_systems/satellite_systems.webp',
  '/assets/sprites/knowledge/science/science.webp',
  '/assets/sprites/knowledge/social_sciences/social_sciences.webp',
  '/assets/sprites/knowledge/special_forces/special_forces.webp',
  '/assets/sprites/knowledge/stealth_secrecy/stealth_secrecy.webp',
  '/assets/sprites/knowledge/steam_engine/steam_engine.webp',
  '/assets/sprites/knowledge/steel/steel.webp',
  '/assets/sprites/knowledge/strategic_warfare/strategic_warfare.webp',
  '/assets/sprites/knowledge/tactics/tactics.webp',
];

export async function prefetchAllSprites() {
  if (!('caches' in window)) return;
  const cache = await caches.open(CACHE_NAME);

  // Fetch in batches of 6 to avoid saturating mobile connections
  for (let i = 0; i < STATIC_SPRITES.length; i += 6) {
    await Promise.allSettled(
      STATIC_SPRITES.slice(i, i + 6).map(async url => {
        const hit = await cache.match(url);
        if (hit) return;
        const res = await fetch(url);
        if (res.ok) await cache.put(url, res);
      })
    );
  }
}
