maps:
- id: live_4_1774129631
  name: Bronze+
  life: 12.0
  hex_map:
  - q: -1
    r: -1
    type: path
  - q: -1
    r: 0
    type: ARROW_TOWER
  - q: -1
    r: 1
    type: FIRE_TOWER
  - q: -1
    r: 2
    type: path
  - q: -1
    r: 3
    type: FIRE_TOWER
  - q: -2
    r: 0
    type: path
  - q: -2
    r: 1
    type: path
  - q: -2
    r: 2
    type: path
  - q: -2
    r: 3
    type: BALLISTA_TOWER
  - q: -3
    r: 1
    type: FIRE_TOWER
  - q: -3
    r: 2
    type: FIRE_TOWER
  - q: -3
    r: 3
    type: BALLISTA_TOWER
  - q: 0
    r: -1
    type: SPIKE_TRAP
  - q: 0
    r: -2
    type: path
  - q: 0
    r: 0
    type: castle
  - q: 0
    r: 1
    type: BALLISTA_TOWER
  - q: 0
    r: 2
    type: path
  - q: 0
    r: 3
    type: ARROW_TOWER
  - q: 1
    r: -1
    type: BALLISTA_TOWER
  - q: 1
    r: -2
    type: path
  - q: 1
    r: 0
    type: path
  - q: 1
    r: 1
    type: ARROW_TOWER
  - q: 1
    r: 2
    type: path
  - q: 2
    r: -1
    type: HEAVY_TOWER
  - q: 2
    r: -2
    type: path
  - q: 2
    r: 0
    type: path
  - q: 2
    r: 1
    type: path
  - q: 3
    r: -1
    type: ARBELESTE_TOWER
  - q: 3
    r: -2
    type: spawnpoint
  - q: 3
    r: 0
    type: ARBELESTE_TOWER
- id: live_4_1774628767
  name: Middle Ages
  hex_map:
  - q: -1
    r: -1
    type: empty
  - q: -1
    r: 0
    type: TAR_TOWER
  - q: -1
    r: 1
    type: BOILING_OIL
  - q: -1
    r: 2
    type: empty
  - q: -1
    r: 3
    type: BOILING_OIL
  - q: -1
    r: 4
    type: empty
  - q: -2
    r: 0
    type: empty
  - q: -2
    r: 1
    type: empty
  - q: -2
    r: 2
    type: empty
  - q: -2
    r: 3
    type: HEAVY_TOWER
  - q: -2
    r: 4
    type: empty
  - q: -3
    r: 1
    type: FIRE_TOWER
  - q: -3
    r: 2
    type: FIRE_TOWER
  - q: -3
    r: 3
    type: BALLISTA_TOWER
  - q: -3
    r: 4
    type: spawnpoint
  - q: 0
    r: -1
    type: HEAVY_TOWER
  - q: 0
    r: -2
    type: empty
  - q: 0
    r: 0
    type: castle
  - q: 0
    r: 1
    type: CATAPULTS
  - q: 0
    r: 2
    type: empty
  - q: 0
    r: 3
    type: HEAVY_TOWER
  - q: 0
    r: 4
    type: empty
  - q: 1
    r: -1
    type: BALLISTA_TOWER
  - q: 1
    r: -2
    type: empty
  - q: 1
    r: 0
    type: empty
  - q: 1
    r: 1
    type: TAR_TOWER
  - q: 1
    r: 2
    type: empty
  - q: 1
    r: 3
    type: BOILING_OIL
  - q: 1
    r: 4
    type: empty
  - q: 2
    r: -1
    type: HEAVY_TOWER
  - q: 2
    r: -2
    type: empty
  - q: 2
    r: 0
    type: empty
  - q: 2
    r: 1
    type: empty
  - q: 2
    r: 2
    type: HEAVY_TOWER
  - q: 2
    r: 3
    type: empty
  - q: 3
    r: -1
    type: ARBELESTE_TOWER
  - q: 3
    r: -2
    type: empty
  - q: 3
    r: 0
    type: ARBELESTE_TOWER
  - q: 3
    r: 1
    type: TAR_TOWER
  - q: 3
    r: 2
    type: empty
  - q: 3
    r: 3
    type: empty
  - q: 4
    r: -1
    type: empty
  - q: 4
    r: -2
    type: empty
  - q: 4
    r: 0
    type: empty
  - q: 4
    r: 1
    type: empty
  life: 16.0
- id: live_7_1774675022
  name: Neolith
  hex_map:
  - q: -1
    r: 1
    type: BASIC_TOWER
  - q: -1
    r: 2
    type: empty
  - q: -1
    r: 3
    type: empty
  - q: 0
    r: 0
    type: castle
  - q: 0
    r: 1
    type: empty
  - q: 0
    r: 2
    type: DOUBLE_SLING_TOWER
  - q: 0
    r: 3
    type: empty
  - q: 1
    r: 0
    type: BASIC_TOWER
  - q: 1
    r: 1
    type: BASIC_TOWER
  - q: 1
    r: 2
    type: empty
  - q: 2
    r: 1
    type: empty
  - q: 2
    r: 0
    type: empty
  - q: 2
    r: -1
    type: spawnpoint
  - q: 2
    r: 2
    type: empty
  life: 10.0
- id: live_4_1774794556
  name: 1 Basic Tower
  hex_map:
  - q: 0
    r: 0
    type: castle
  - q: 0
    r: 1
    type: BASIC_TOWER
  - q: 1
    r: 0
    type: spawnpoint
  life: 10.0
- id: live_4_1774794588
  name: '1 Basic Tower (len: 3)'
  hex_map:
  - q: 0
    r: 0
    type: castle
  - q: 0
    r: 1
    type: BASIC_TOWER
  - q: 1
    r: 0
    type: empty
  - q: 1
    r: 1
    type: spawnpoint
  life: 10.0
- id: live_4_1774795155
  name: '1 Basic Tower (len: 4)'
  hex_map:
  - q: 0
    r: 0
    type: castle
  - q: 0
    r: 1
    type: BASIC_TOWER
  - q: 1
    r: 0
    type: empty
  - q: 1
    r: 1
    type: empty
  - q: 0
    r: 2
    type: spawnpoint
  - q: 2
    r: 0
    type: empty
  life: 10.0
- id: live_4_1774795443
  name: '2 Basic Tower (len: 4)'
  hex_map:
  - q: 0
    r: 0
    type: castle
  - q: 0
    r: 1
    type: BASIC_TOWER
  - q: 0
    r: 2
    type: spawnpoint
  - q: 1
    r: 0
    type: empty
  - q: 1
    r: 1
    type: empty
  - q: 2
    r: 0
    type: BASIC_TOWER
  life: 10.0
- id: live_12_1775476137
  name: Schafshügel (Bronze)
  hex_map:
  - q: -1
    r: -1
    type: empty
  - q: -1
    r: -2
    type: empty
  - q: -1
    r: 0
    type: FIRE_TOWER
  - q: -1
    r: 1
    type: BALLISTA_TOWER
  - q: -1
    r: 2
    type: empty
  - q: -2
    r: -1
    type: BALLISTA_TOWER
  - q: -2
    r: 0
    type: FIRE_TOWER
  - q: -2
    r: 1
    type: spawnpoint
  - q: -2
    r: 2
    type: empty
  - q: -2
    r: 3
    type: BALLISTA_TOWER
  - q: -3
    r: 2
    type: ARROW_TOWER
  - q: 0
    r: -1
    type: empty
  - q: 0
    r: -2
    type: FIRE_TOWER
  - q: 0
    r: -3
    type: castle
  - q: 0
    r: 0
    type: CATAPULTS
  - q: 0
    r: 1
    type: empty
  - q: 0
    r: 2
    type: FIRE_TOWER
  - q: 1
    r: -1
    type: CATAPULTS
  - q: 1
    r: -2
    type: empty
  - q: 1
    r: -3
    type: BALLISTA_TOWER
  - q: 1
    r: 0
    type: BALLISTA_TOWER
  - q: 1
    r: 1
    type: empty
  - q: 2
    r: -1
    type: empty
  - q: 2
    r: -2
    type: empty
  - q: 2
    r: 0
    type: empty
  - q: 3
    r: -2
    type: CATAPULTS
  life: 12.0
- id: live_15_1776279998
  name: Fruit Republic (late neo)
  hex_map:
  - q: -1
    r: 2
    type: empty
  - q: -1
    r: 3
    type: BALLISTA_TOWER
  - q: -1
    r: 4
    type: spawnpoint
  - q: -2
    r: 2
    type: FIRE_TOWER
  - q: -2
    r: 3
    type: empty
  - q: -2
    r: 4
    type: empty
  - q: 0
    r: 0
    type: castle
  - q: 0
    r: 1
    type: BASIC_TOWER
  - q: 0
    r: 2
    type: empty
  - q: 0
    r: 3
    type: DOUBLE_SLING_TOWER
  - q: 1
    r: 0
    type: empty
  - q: 1
    r: 1
    type: SPIKE_TRAP
  - q: 1
    r: 2
    type: empty
  - q: 2
    r: -1
    type: DOUBLE_SLING_TOWER
  - q: 2
    r: 0
    type: empty
  - q: 2
    r: 1
    type: empty
  life: 10.0
- id: live_7_1776280037
  name: Limperium (Late renn)
  hex_map:
  - q: -1
    r: 0
    type: CANNON_TOWER
  - q: -1
    r: 1
    type: empty
  - q: -1
    r: 2
    type: ICE_TOWER
  - q: -1
    r: 3
    type: empty
  - q: -1
    r: 4
    type: RIFLE_TOWER
  - q: -1
    r: 5
    type: empty
  - q: -1
    r: 6
    type: RIFLE_TOWER
  - q: -1
    r: 7
    type: empty
  - q: -1
    r: 8
    type: RIFLE_TOWER
  - q: -1
    r: 9
    type: empty
  - q: -2
    r: 1
    type: castle
  - q: -2
    r: 10
    type: RIFLE_TOWER
  - q: -2
    r: 2
    type: RIFLE_TOWER
  - q: -2
    r: 3
    type: CANNON_TOWER
  - q: -2
    r: 4
    type: empty
  - q: -2
    r: 5
    type: empty
  - q: -2
    r: 6
    type: ICE_TOWER
  - q: -2
    r: 7
    type: RIFLE_TOWER
  - q: -2
    r: 8
    type: empty
  - q: -2
    r: 9
    type: empty
  - q: 0
    r: -1
    type: RIFLE_TOWER
  - q: 0
    r: 0
    type: empty
  - q: 0
    r: 1
    type: RIFLE_TOWER
  - q: 0
    r: 2
    type: empty
  - q: 0
    r: 3
    type: CANNON_TOWER
  - q: 0
    r: 4
    type: empty
  - q: 0
    r: 5
    type: RIFLE_TOWER
  - q: 0
    r: 6
    type: empty
  - q: 0
    r: 7
    type: ICE_TOWER
  - q: 0
    r: 8
    type: empty
  - q: 1
    r: -1
    type: empty
  - q: 1
    r: -2
    type: RIFLE_TOWER
  - q: 1
    r: 0
    type: RIFLE_TOWER
  - q: 1
    r: 1
    type: empty
  - q: 1
    r: 2
    type: RIFLE_TOWER
  - q: 1
    r: 3
    type: empty
  - q: 1
    r: 4
    type: RIFLE_TOWER
  - q: 1
    r: 5
    type: empty
  - q: 1
    r: 6
    type: RIFLE_TOWER
  - q: 1
    r: 7
    type: empty
  - q: 1
    r: 8
    type: CANNON_TOWER
  - q: 2
    r: -1
    type: CANNON_TOWER
  - q: 2
    r: -2
    type: empty
  - q: 2
    r: -3
    type: ICE_TOWER
  - q: 2
    r: 0
    type: empty
  - q: 2
    r: 1
    type: ICE_TOWER
  - q: 2
    r: 2
    type: empty
  - q: 2
    r: 3
    type: ICE_TOWER
  - q: 2
    r: 4
    type: empty
  - q: 2
    r: 5
    type: RIFLE_TOWER
  - q: 2
    r: 6
    type: empty
  - q: 2
    r: 7
    type: COLD_TOWER
  - q: 2
    r: 8
    type: spawnpoint
  - q: 3
    r: -1
    type: empty
  - q: 3
    r: -2
    type: empty
  - q: 3
    r: -3
    type: RIFLE_TOWER
  - q: 3
    r: 0
    type: RIFLE_TOWER
  - q: 3
    r: 1
    type: RIFLE_TOWER
  - q: 3
    r: 2
    type: empty
  - q: 3
    r: 3
    type: empty
  - q: 3
    r: 4
    type: CANNON_TOWER
  - q: 3
    r: 5
    type: ICE_TOWER
  - q: 3
    r: 6
    type: empty
  - q: 3
    r: 7
    type: empty
  life: 24.0
- id: live_16_1776282839
  name: Imperium Aperol 🍹 (pure neo)
  hex_map:
  - q: 0
    r: 0
    type: empty
  - q: 0
    r: 1
    type: spawnpoint
  - q: 0
    r: 2
    type: DOUBLE_SLING_TOWER
  - q: 1
    r: -1
    type: empty
  - q: 1
    r: 0
    type: SPIKE_TRAP
  - q: 1
    r: 1
    type: DOUBLE_SLING_TOWER
  - q: 1
    r: 2
    type: DOUBLE_SLING_TOWER
  - q: 1
    r: 3
    type: DOUBLE_SLING_TOWER
  - q: 2
    r: -1
    type: empty
  - q: 2
    r: 0
    type: empty
  - q: 2
    r: 1
    type: empty
  - q: 2
    r: 2
    type: empty
  - q: 2
    r: 3
    type: empty
  - q: 3
    r: -1
    type: DOUBLE_SLING_TOWER
  - q: 3
    r: -2
    type: DOUBLE_SLING_TOWER
  - q: 3
    r: 0
    type: DOUBLE_SLING_TOWER
  - q: 3
    r: 1
    type: DOUBLE_SLING_TOWER
  - q: 3
    r: 2
    type: DOUBLE_SLING_TOWER
  - q: 3
    r: 3
    type: empty
  - q: 4
    r: 2
    type: castle
  life: 10.0
- id: live_3_1776283370
  name: Bikini Bottom (early Indy)
  hex_map:
  - q: -1
    r: -1
    type: spawnpoint
  - q: -1
    r: -2
    type: RIFLE_TOWER
  - q: -1
    r: 0
    type: CANNON_TOWER
  - q: -1
    r: 1
    type: empty
  - q: -1
    r: 2
    type: FLAME_THROWER
  - q: -1
    r: 3
    type: empty
  - q: -1
    r: 4
    type: HEAVY_TOWER
  - q: -2
    r: -1
    type: RIFLE_TOWER
  - q: -2
    r: 0
    type: RIFLE_TOWER
  - q: -2
    r: 1
    type: empty
  - q: -2
    r: 2
    type: RIFLE_TOWER
  - q: -2
    r: 3
    type: empty
  - q: -2
    r: 4
    type: ICE_TOWER
  - q: -3
    r: 0
    type: ICE_TOWER
  - q: -3
    r: 1
    type: RIFLE_TOWER
  - q: -3
    r: 2
    type: empty
  - q: -3
    r: 3
    type: empty
  - q: -3
    r: 4
    type: RIFLE_TOWER
  - q: -4
    r: 1
    type: HEAVY_TOWER
  - q: -4
    r: 2
    type: COLD_TOWER
  - q: -4
    r: 3
    type: RIFLE_TOWER
  - q: -4
    r: 4
    type: RIFLE_TOWER
  - q: 0
    r: -1
    type: empty
  - q: 0
    r: -2
    type: RIFLE_TOWER
  - q: 0
    r: 0
    type: COLD_TOWER
  - q: 0
    r: 1
    type: empty
  - q: 0
    r: 2
    type: COLD_TOWER
  - q: 0
    r: 3
    type: empty
  - q: 0
    r: 4
    type: FLAME_THROWER
  - q: 1
    r: -1
    type: empty
  - q: 1
    r: -2
    type: ICE_TOWER
  - q: 1
    r: 0
    type: FLAME_THROWER
  - q: 1
    r: 1
    type: empty
  - q: 1
    r: 2
    type: BOILING_OIL
  - q: 1
    r: 3
    type: empty
  - q: 1
    r: 4
    type: RIFLE_TOWER
  - q: 2
    r: -1
    type: empty
  - q: 2
    r: -2
    type: RIFLE_TOWER
  - q: 2
    r: 0
    type: ICE_TOWER
  - q: 2
    r: 1
    type: empty
  - q: 2
    r: 2
    type: FLAME_THROWER
  - q: 2
    r: 3
    type: empty
  - q: 2
    r: 4
    type: RIFLE_TOWER
  - q: 3
    r: -1
    type: empty
  - q: 3
    r: -2
    type: FLAME_THROWER
  - q: 3
    r: 0
    type: FLAME_THROWER
  - q: 3
    r: 1
    type: empty
  - q: 3
    r: 2
    type: RIFLE_TOWER
  - q: 3
    r: 3
    type: empty
  - q: 3
    r: 4
    type: ICE_TOWER
  - q: 4
    r: -1
    type: empty
  - q: 4
    r: -2
    type: HEAVY_TOWER
  - q: 4
    r: 0
    type: CANNON_TOWER
  - q: 4
    r: 1
    type: empty
  - q: 4
    r: 2
    type: COLD_TOWER
  - q: 4
    r: 3
    type: empty
  - q: 4
    r: 4
    type: RIFLE_TOWER
  - q: 5
    r: -1
    type: empty
  - q: 5
    r: -2
    type: COLD_TOWER
  - q: 5
    r: 0
    type: RIFLE_TOWER
  - q: 5
    r: 1
    type: empty
  - q: 5
    r: 2
    type: RIFLE_TOWER
  - q: 5
    r: 3
    type: castle
  - q: 5
    r: 4
    type: RIFLE_TOWER
  - q: 6
    r: -1
    type: empty
  - q: 6
    r: -2
    type: HEAVY_TOWER
  - q: 6
    r: 0
    type: COLD_TOWER
  - q: 6
    r: 1
    type: empty
  - q: 6
    r: 2
    type: RIFLE_TOWER
  - q: 6
    r: 3
    type: RIFLE_TOWER
  - q: 7
    r: -1
    type: empty
  - q: 7
    r: -2
    type: ICE_TOWER
  - q: 7
    r: 0
    type: empty
  - q: 7
    r: 1
    type: RIFLE_TOWER
  - q: 7
    r: 2
    type: ICE_TOWER
  - q: 8
    r: -1
    type: RIFLE_TOWER
  - q: 8
    r: -2
    type: RIFLE_TOWER
  - q: 8
    r: 0
    type: ICE_TOWER
  - q: 8
    r: 1
    type: ICE_TOWER
  life: 26.0
